services:
  app:
    image: openjdk:11-jre-slim
    container_name: springboot-app
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mareoenviosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: mareoenviosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
